In [2]:
import numpy as np
import json
import sys
sys.path.append('../')
from src import agents, environment

In [12]:
REPLAY_JSON_FN = '/vol/08822801/shawn.chen/subtraction_game/minimaxV2osla_minimax5_seed1104_date0615b/play_000008.json'


with open(REPLAY_JSON_FN, 'r') as f:
    data = json.load(f)

In [14]:
def add_action(board, action):
    row_col_idx, sub_val = action
    num_rows = board.shape[0]
    if row_col_idx < num_rows:
        board[row_col_idx] += sub_val
    else:
        board[:, row_col_idx - num_rows] += sub_val

In [ ]:
board = np.array(data['end_board'])
actions_p1 = data['actions_p1']
actions_p2 = data['actions_p2']
print(board)

index_p1 = len(actions_p1) - 1
index_p2 = len(actions_p2) - 1
if len(actions_p1) > len(actions_p2):
    print(actions_p1[index_p1])
    add_action(board, actions_p1[index_p1])
    index_p1 -= 1
    print(board)
for idx in range(index_p1):
    print('p2:', actions_p2[index_p2])
    add_action(board, actions_p2[index_p2])
    index_p2 -= 1
    print(board)
    print('p1:', actions_p1[index_p1])
    add_action(board, actions_p1[index_p1])
    index_p1 -= 1
    print(board)

In [77]:
mx = agents.Minimax(max_depth=9)  # max_depth=5 will give different results
env = environment.SubtractionRule()
#state = np.array([[13, 0, 25], [9, 4, 8], [0, 0, 8]])
#state = np.array([[13, 0, 26], [10, 5, 10], [0, 0, 9]])
state = np.array([[13, 0, 27], [13, 8, 14], [0, 0, 10]])

#state = np.array([[13, 0, 27], [12, 7, 13], [0, 0, 10]])

#state = np.array([[13, 0, 27], [7, 2, 12], [0, 0, 10]])
#state = np.array([[13, 0, 23], [11, 6, 8], [0, 0, 6]])
#state = np.array([[13, 0, 19], [11, 6, 4], [0, 0, 2]])

mx.act(state, env.actions(state))

(5, 2)

In [78]:
for child in mx.root.children:
    print(child.action, child.value)

(1, 1) 14.0
(1, 2) 15.0
(1, 3) -5.0
(5, 1) 15.0
(5, 2) -13.0


In [48]:
for child in mx.root.children[0].children:
    print(child.action, child.value)

(1, 1) -10.0
(1, 2) -10.0
(1, 3) -14.0
(5, 1) -10.0
(5, 2) -12.0
(5, 3) -14.0


In [10]:
for child in mx.root.children[0].children[0].children:
    print(child.action, child.value)

(1, 1) 1.0
(1, 2) 2.0
(1, 3) 15.0
(5, 1) 1.0
(5, 2) 2.0
(5, 3) 3.0


In [11]:
for child in mx.root.children[0].children[0].children[0].children:
    print(child.action, child.value)

(1, 1) 1.0
(1, 2) 0.0
(1, 3) -1.0
(5, 1) 1.0
(5, 2) 0.0
(5, 3) -1.0


In [16]:
for child in mx.root.children[0].children[0].children[0].children[0].children:
    print(child.state, child.action, child.value)

[[13  0 27]
 [ 8  3  9]
 [ 0  0 10]] (1, 1) 1.0
[[13  0 27]
 [ 7  2  8]
 [ 0  0 10]] (1, 2) 2.0
[[13  0 27]
 [ 6  1  7]
 [ 0  0 10]] (1, 3) 3.0
[[13  0 26]
 [ 9  4  9]
 [ 0  0  9]] (5, 1) 1.0
[[13  0 25]
 [ 9  4  8]
 [ 0  0  8]] (5, 2) 2.0
[[13  0 24]
 [ 9  4  7]
 [ 0  0  7]] (5, 3) 3.0


In [14]:
for child in mx.root.children[0].children[0].children[0].children[0].children[0].children:
    print(child.state, child.action, child.value)